.PHONY: make
make:
	make -j -C BetaScopeWaveformAna/
	make -j -C SelfTrigger/
	#make -j -C ArgoneXrayAna/

.PHONY: clean
clean:
	make clean -C BetaScopeWaveformAna/
	make clean -C SelfTrigger/
	#make clean -C ArgoneXrayAna/
