.PHONY: clean
clean:
	current_path=`pwd`
	cd ../General && make $@ && cd ${current_path}

	cd ../BetaScope_Driver && make $@ && cd ${current_path}

	cd ../BetaScope_Ana && make $@ && cd ${current_path}

	cd betaScopePlot && make $@ && cd ${current_path}
