name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checktout@v2
   
   - name: Build the Docker image
      run: docker run --rm -it rootproject/root
      
