name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rootproject/root:6.22.00-fedora32
      options: --entrypoint /bin/bash
    steps:
      #- name: setup docker
      #  run: docker run -t rootproject/root:latest bash
      #- name: run docker
      #  run: docker exec -it root_docker /bin/bash
      #- name: chsh
      #  run: chsh -s /usr/bin/bash
      - name: shell
        run: echo $SHELL
      - name: pull repo
        uses: actions/checkout@v2
      #- name: update 
      #  run: dnf -y update
      - name: install g++-8
        run: dnf -y install g++
      - name: install boost lib
        run: dnf -y install boost-devel      
      - name: install format lib
        run: dnf -y install fmt-devel
      - name: setup beta analysis
        run: cd scripts ; chmod 777 setup.sh ; ./setup.sh
      - name: alias
        run : alias -p
      - name: run beta analysis
        run: run_WaveformAna -config WaveformAna.ini
        
