name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: rootproject/root:6.22.00-ubuntu20.04
    steps:
      - name: pull repo
        uses: actions/checkout@v2
      - name: setup beta analysis
        run: cd scripts ; source setup.sh
        
