name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    #container: 
      #image: rootproject/root:latest
      #options: --entrypoint=bash
    steps:
      - name: setup docker
        run: docker run --name root_docker --rm -t -t rootproject/root:latest bash
      - name: run docker
        run: docker exec -it root_docker /bin/bash
      - name: ls
        run: ls .
      - name: pull repo
        uses: actions/checkout@v2
      - name: update 
        run: apt-get update && apt-get install --assume-yes apt-utils
      - name: install g++-8
        run: apt-get --assume-yes install g++-8
      - name: install boost lib
        run: apt-get --assume-yes install libboost-all-dev      
      - name: install format lib
        run: apt-get --assume-yes install libfmt-dev
      - name: setup beta analysis
        run: cd scripts ; source setup.sh
        
