name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rootproject/root:latest
      options: --entrypoint "/bin/bash -c"
    steps:
      - name: pull repo
        uses: actions/checkout@v2
      - name: update 
        run: apt-get update && apt-get install --assume-yes apt-utils
      - name: install g++-8
        run: apt-get --assume-yes install g++-8
      - name: install boost lib
        run: apt-get --assume-yes install libboost-all-dev      
      - name: install format lib
        run: apt-get --assume-yes install libfmt-dev
      - name: setup beta analysis
        run: cd scripts ; chmod 777 setup_sh.sh; . ./setup_sh.sh
      - name: ls
        run: ls BetaScope_Ana/BetaScopeWaveformAna/bin/
      - name: testing run_WaveformAna
        run: run_WaveformAna -config WaveformAna.ini
        
