name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rootproject/root:latest
      options: --entrypoint /bin/bash 
    steps:
      #- name: setup docker
      #  run: docker run -t rootproject/root:latest bash
      #- name: run docker
      #  run: docker exec -it root_docker /bin/bash
      #- name: chsh
      #  run: chsh -s /usr/bin/bash
      - name: shell
        run: echo $SHELL ; echo $0
      - name: pull repo
        uses: actions/checkout@v2
      - name: update 
        run: apt-get -y update
      - name: install g++-8
        run: apt-get -y install g++
      - name: install boost lib
        run: apt-get -y install libboost-all-dev      
      - name: install format lib
        run: apt-get -y install libfmt-dev
      - name: install wget
        run: apt-get -y install wget
      - name: install zip
        run: apt-get -y install zip
      - name: fft
        run: apt-get -y install libfftw3-dev
      - name: pip
        run: apt-get -y install python3-pip 
      - name: python openpyxl
        run: python3 -m pip install -u openpyxl
      - name: setup beta analysis
        run: cd scripts ; /bin/bash -c "source setup.sh"
      - name: echo
        run: echo $BETASCOPE_SCRIPTS
      - name: test beta analysis
        run: /bin/bash -c "source scripts/test.sh"
        
