name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: rootproject/root:6.22.00-ubuntu20.04
    steps:
      - name: pull repo
        uses: actions/checkout@v2
      - name: update 
        run: apt-get update && apt-get install --assume-yes apt-utils && apt-get install --assume-yes bash
      - name: bash
        run: chsh -s /bin/bash
      - name: install g++-8
        run: apt-get --assume-yes install g++-8
      - name: install boost lib
        run: apt-get --assume-yes install libboost-all-dev      
      - name: install format lib
        run: apt-get --assume-yes install libfmt-dev
      - name: setup beta analysis
        run: cd scripts ; chmod 777 setup.sh ; ./setup.sh
      - name: testing run_WaveformAna
        run: run_WaveformAna -config WaveformAna.ini
        
