name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build docker image
        run: docker build --file .github/workflows/dockerfile -tag my-image-name:testing
  Test:
    steps:
      - name: pull repo
        uses: actions/checkout@v2
      - name: update 
        run: apt-get update && apt-get install --assume-yes apt-utils
      - name: install g++-8
        run: apt-get --assume-yes install g++-8
      - name: install boost lib
        run: apt-get --assume-yes install libboost-all-dev      
      - name: install format lib
        run: apt-get --assume-yes install libfmt-dev
      - name: setup beta analysis
        run: cd scripts ; chmod 777 setup.sh ; ./setup.sh
      - name: testing run_WaveformAna
        run: run_WaveformAna -config WaveformAna.ini
        
