name: Docker Image CI

on: [push]

jobs:
  
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      -name: checkout root repo
       container:
        image: "rootprojet/6.22.00-ubuntu20.04"
        
