name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rootproject/root:latest
      options: --entrypoint=bash
    steps:
      #- name: setup docker
      #  run: docker run --name root_docker --rm -t -t rootproject/root:latest bash
      #- name: run docker
      #  run: docker exec -it root_docker /bin/bash
      - name: chsh
        run: chsh -s /bin/bash
      - name: ls
        run: echo $SHELL ;
      - name: shell
        run: alias hi='hi'
      - name: print
        run: alias -p
      - name: pull repo
        uses: actions/checkout@v2
      - name: update 
        run: apt-get update && apt-get install --assume-yes apt-utils
      - name: install g++-8
        run: apt-get --assume-yes install g++-8
      - name: install boost lib
        run: apt-get --assume-yes install libboost-all-dev      
      - name: install format lib
        run: apt-get --assume-yes install libfmt-dev
      - name: setup beta analysis
        run: cd scripts ; chsh -s /bin/bash ; source setup.sh
        
