name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Build the Docker image
      run: docker run --rm rootproject/root
    - uses: actions/checkout@v2
      
