name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rootproject/root:6.20.06-fedora32
      options: --entrypoint /bin/bash
    steps:
      - name: pull repo
        uses: actions/checkout@v2
      - name: update 
        run: dnf update && dnf install --assume-yes apt-utils
      - name: install g++-8
        run: dnf --assume-yes install g++-8
      - name: install boost lib
        run: dnf --assume-yes install libboost-all-dev      
      - name: install format lib
        run: dnf --assume-yes install libfmt-dev
      - name: setup beta analysis
        run: cd scripts ; chmod 777 setup_sh.sh; . ./setup_sh.sh
      - name: ls
        run: alias
      - name: testing run_WaveformAna
        run: run_WaveformAna -config WaveformAna.ini
        
